language: c
sudo: required
dist: trusty
before_install:
    - sudo add-apt-repository -y ppa:snaipewastaken/ppa
    - sudo apt-get -y update
    - sudo apt-get -y install criterion-dev
install: "make test"
before_script: "mkdir build"
script: "./build/test"
