language: c
sudo: required
dist: trusty
addons:
    apt:
        sources:
            - ubuntu-toolchain-r-test
        packages:
            - gcc-5
before_install:
    - sudo add-apt-repository -y ppa:snaipewastaken/ppa
    - sudo apt-get -y update
    - sudo apt-get -y install criterion-dev
    - pip install --user cpp-coveralls
    - mkdir build
    - gcc --version
install: "make TEST=y all-tests"
script: "./build/all-tests"
after_success:
    - coveralls --exclude lib --exclude tests --gcov-options '\-lp'
