language: c
sudo: required
dist: trusty
before_install:
    - sudo add-apt-repository -y ppa:snaipewastaken/ppa
    - sudo apt-get -y update
    - sudo apt-get -y install criterion-dev
    - mkdir build
install: "make test"
script: "./build/test"
